language: cpp

branches:
  only:
    - master
    - develop

compiler:
  - gcc

before_script:
  - ssudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update
  - sudo apt-get install -qq cmake
  - mkdir build
  - cd build
  - cmake ..

script:
  - make check

notifications:
  email:
    on_success: change
    on_failure: change
