language: c++

compiler:
  - gcc
  - clang

#os:
#  - linux
#  - osx

env:
  global:
    - secure: "fzcPJLIK8JqmE7tnIkgZbl4I9nGmcN89PhI2IpBn1CGbwQfh4DQthIuKJHdyWZWHwZkx94WH31mDnvEXxPDumCwgFaTxp/YR8hIsA6cp0nWF2XmGCdksH9ON1EF9WO16J1t7XspHMAebiEm+d8tjXizJM6TYA+YhdejcAr09chNootEO1OTxhKoptZtNZUTAG5yeOvPZSAPUqVByKpV8roYnfYbSs4t1v15XeIj7J4WYHjy0Nvaq6xWfgxw7bkuLIVFPtLrzjfEi1lvuowFqSa0VqgXePhODpKM1EItdjDlxqS9cpA9P8EJFK3X/V9Wy56V6oSWfyJivM1AmJ5Ra/3ERsKTmfLV/+ZSPqobRPOxd6FC+KyPIXvcNz8ItVrY1Llu9oEKygQuZ/X5ax0WTOu0j1dzMqTNijh8+7VU2ajvD1sA13IXF3sJz1zsEhDqIvJcpOKO/4MlJIViOSVk/QISgfslquEkCUGj8dmCWo1T2YyR1jNANF8Ihqh/wPokvGQPENcV2N+zlLnX6Ca/qi72JPfaXLKWH+JdT7dTjDqBXXV/yppHU8HrJYtTJfuB81SpsbJge+nSpcpXH7/u+D9NF9KF7KMP1GcBtRpOGRNhIKsXbBEWQ3or5cfBDGGJnsfpUEFxGTFD5Z690OjLIiNoXPbdt8T2Vha5cC/hmRMs="

branches:
  only:
    - master
    - develop

addons:
  coverity_scan:
    project:
      name: "shaduzlabs/unmidify"
      description: "Build submitted via Travis CI"
    notification_email: shaduz@shaduzlabs.com
    build_command_prepend: "make clean"
    build_command:   "make -j2 check"
    branch_pattern: master

script: cmake . && make -j2 check

# source: https://github.com/OpenLightingProject/ola/blob/master/.travis.yml
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:h-rayflood/gcc-upper -y
  - sudo add-apt-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" -y
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository ppa:ubuntu-cloud-archive/icehouse-staging -y
  - sudo apt-get update -qq

  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
#Remove the old g++/gcc to ensure we're using the latest ones
  - if [ "$CXX" = "g++-4.9" ]; then sudo rm /usr/bin/g++; sudo rm /usr/bin/gcc; fi

  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq clang-3.8; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
#Remove the old clang to ensure we're using the latest ones
  - if [ "$CXX" = "clang++-3.8" ]; then sudo rm /usr/local/clang-3.4/bin/clang; sudo rm /usr/local/clang-3.4/bin/clang++; fi

#Report the compiler version
  - $CXX --version

  - sudo apt-get update -qq
  - sudo apt-get install libboost-thread-dev libboost-system-dev

install:
  # CMake 3.2.1
  - CMAKE_URL=https://cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz
  - mkdir cmake
  - $WGET -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${PWD}/cmake/bin:${PATH}

  # Doxygen 1.8.9.1
  - DOXYGEN_URL="http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.9.1.linux.bin.tar.gz"
  - mkdir doxygen && travis_retry wget --quiet -O - ${DOXYGEN_URL} | tar --strip-components=1 -xz -C doxygen
  - export PATH=${PWD}/doxygen/bin:${PATH}

notifications:
  email:
    on_success: change
    on_failure: change
