language: cpp

branches:
  only:
    - master
    - develop

compiler:
  - gcc

before_script:
  - sudo add-apt-repository --yes ppa:george-edison55/precise-backports
  - sudo apt-get update
  - sudo apt-get install -qq cmake
  - mkdir build
  - cd build
  - cmake ..

script:
  - make check

notifications:
  email:
    on_success: change
    on_failure: change
