language: cpp

compiler:
  - gcc

before_script:
  - sudo apt-get install cmake
  - mkdir build
  - cd build
  - cmake ..

script:
  - make check

notifications:
  email:
    on_success: change
    on_failure: change
