language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - doxygen
      - gcc-4.8
      - g++-4.8
      - clang
branches:
  only:
    - master
    - develop

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make check

notifications:
  email:
    on_success: change
    on_failure: change
